import type { SpeciesInfo } from "../types";

function antWikiUrl(genus: string, species: string): string {
  return `https://www.antwiki.org/wiki/${genus}_${species}`;
}

export const ALL_SPECIES: Record<string, SpeciesInfo> = {
  "Prenolepis nitens": {
    scientificName: "Prenolepis nitens",
    commonName: "Winter Ant",
    queenSize: "4.5–5.5 mm",
    lifestyle: "Subterranean, cold-adapted; queens found under stones in early spring",
    society: "Monogynous, small to medium colonies",
    diet: "Honeydew, small invertebrates, seeds",
    antWikiUrl: antWikiUrl("Prenolepis", "nitens"),
  },
  "Messor structor": {
    scientificName: "Messor structor",
    commonName: "Harvester Ant",
    queenSize: "9–11 mm",
    lifestyle: "Ground-dwelling seed harvester; nests in dry, warm soil",
    society: "Monogynous to weakly polygynous, large colonies",
    diet: "Primarily seeds (granivorous), supplemented with insects",
    antWikiUrl: antWikiUrl("Messor", "structor"),
  },
  "Camponotus fallax": {
    scientificName: "Camponotus fallax",
    commonName: "Shy Carpenter Ant",
    queenSize: "9–10 mm",
    lifestyle: "Arboreal; nests in dead branches and hollow twigs",
    society: "Monogynous, small colonies (few hundred workers)",
    diet: "Honeydew, insects",
    antWikiUrl: antWikiUrl("Camponotus", "fallax"),
  },
  "Camponotus piceus": {
    scientificName: "Camponotus piceus",
    commonName: "Pitch-black Carpenter Ant",
    queenSize: "9–11 mm",
    lifestyle: "Ground-nesting in warm, dry habitats; under stones",
    society: "Monogynous, small to medium colonies",
    diet: "Honeydew, insects, nectar",
    antWikiUrl: antWikiUrl("Camponotus", "piceus"),
  },
  "Camponotus vagus": {
    scientificName: "Camponotus vagus",
    commonName: "Large Black Carpenter Ant",
    queenSize: "14–16 mm",
    lifestyle: "Nests in dead wood, stumps, and old timber structures",
    society: "Monogynous, large colonies (up to 10,000 workers)",
    diet: "Honeydew, insects, plant sap",
    antWikiUrl: antWikiUrl("Camponotus", "vagus"),
  },
  "Camponotus ligniperda": {
    scientificName: "Camponotus ligniperda",
    commonName: "Red-chested Carpenter Ant",
    queenSize: "15–18 mm",
    lifestyle: "Nests in decaying wood at ground level; largest Central European ant",
    society: "Monogynous, large colonies (up to 10,000+ workers)",
    diet: "Honeydew, insects, tree sap",
    antWikiUrl: antWikiUrl("Camponotus", "ligniperda"),
  },
  "Camponotus aethiops": {
    scientificName: "Camponotus aethiops",
    commonName: "Black-bellied Carpenter Ant",
    queenSize: "10–12 mm",
    lifestyle: "Ground-nesting in warm, dry, sun-exposed habitats",
    society: "Monogynous, medium colonies",
    diet: "Honeydew, insects, nectar",
    antWikiUrl: antWikiUrl("Camponotus", "aethiops"),
  },
  "Formica rufa": {
    scientificName: "Formica rufa",
    commonName: "Red Wood Ant",
    queenSize: "10–12 mm",
    lifestyle: "Builds large mound nests in forests from pine needles and debris",
    society: "Polygynous, supercolonies possible (hundreds of thousands of workers)",
    diet: "Honeydew (primary), insects, tree sap",
    antWikiUrl: antWikiUrl("Formica", "rufa"),
  },
  "Formica sanguinea": {
    scientificName: "Formica sanguinea",
    commonName: "Blood-red Ant (Slave-maker)",
    queenSize: "9–11 mm",
    lifestyle: "Facultative slave-maker; raids nests of other Formica species",
    society: "Monogynous to polygynous, medium to large colonies",
    diet: "Honeydew, insects, raided brood",
    antWikiUrl: antWikiUrl("Formica", "sanguinea"),
  },
  "Manica rubida": {
    scientificName: "Manica rubida",
    commonName: "Large Red Mountain Ant",
    queenSize: "8–10 mm",
    lifestyle: "Montane species; nests under stones in alpine meadows and gravel",
    society: "Monogynous, small to medium colonies",
    diet: "Insects, scavenging, some honeydew",
    antWikiUrl: antWikiUrl("Manica", "rubida"),
  },
  "Tapinoma erraticum": {
    scientificName: "Tapinoma erraticum",
    commonName: "Erratic Ant",
    queenSize: "4–5 mm",
    lifestyle: "Thermophilic; nests in dry, sun-exposed soil and under flat stones",
    society: "Polygynous, medium to large colonies",
    diet: "Honeydew, nectar, small insects",
    antWikiUrl: antWikiUrl("Tapinoma", "erraticum"),
  },
  "Lasius niger": {
    scientificName: "Lasius niger",
    commonName: "Black Garden Ant",
    queenSize: "8–9 mm",
    lifestyle: "Ubiquitous; nests in soil, under pavements, in lawns",
    society: "Monogynous, very large colonies (up to 40,000 workers)",
    diet: "Honeydew (primary), insects, sweet substances",
    antWikiUrl: antWikiUrl("Lasius", "niger"),
  },
  "Lasius flavus": {
    scientificName: "Lasius flavus",
    commonName: "Yellow Meadow Ant",
    queenSize: "7–9 mm",
    lifestyle: "Subterranean; builds prominent mound nests in meadows",
    society: "Monogynous to polygynous, large colonies",
    diet: "Honeydew from root aphids (almost exclusively)",
    antWikiUrl: antWikiUrl("Lasius", "flavus"),
  },
  "Lasius emarginatus": {
    scientificName: "Lasius emarginatus",
    commonName: "Bicolored Garden Ant",
    queenSize: "8–9 mm",
    lifestyle: "Nests in stone walls, rock crevices, and building facades",
    society: "Monogynous, medium to large colonies",
    diet: "Honeydew, insects, nectar",
    antWikiUrl: antWikiUrl("Lasius", "emarginatus"),
  },
  "Tetramorium caespitum": {
    scientificName: "Tetramorium caespitum",
    commonName: "Pavement Ant",
    queenSize: "6–8 mm",
    lifestyle: "Ground-nesting; under pavements, in cracks, and in lawns",
    society: "Monogynous, medium to large colonies",
    diet: "Omnivorous — seeds, insects, honeydew, human food scraps",
    antWikiUrl: antWikiUrl("Tetramorium", "caespitum"),
  },
  "Myrmica rubra": {
    scientificName: "Myrmica rubra",
    commonName: "European Fire Ant",
    queenSize: "5–6 mm",
    lifestyle: "Ground-nesting in moist habitats; under stones, logs, and moss",
    society: "Polygynous, medium to large colonies",
    diet: "Insects, honeydew, seeds, nectar",
    antWikiUrl: antWikiUrl("Myrmica", "rubra"),
  },
  "Formica fusca": {
    scientificName: "Formica fusca",
    commonName: "Silky Ant",
    queenSize: "8–10 mm",
    lifestyle: "Ground-nesting; common host for social parasites and slave-makers",
    society: "Monogynous to polygynous, medium colonies",
    diet: "Honeydew, insects, nectar",
    antWikiUrl: antWikiUrl("Formica", "fusca"),
  },
  "Solenopsis fugax": {
    scientificName: "Solenopsis fugax",
    commonName: "Thief Ant",
    queenSize: "5–7 mm",
    lifestyle: "Tiny subterranean species; builds tunnels into nests of larger ants to steal brood",
    society: "Polygynous, large colonies (hard to observe)",
    diet: "Brood of other ants (kleptobiont), small insects, oily substances",
    antWikiUrl: antWikiUrl("Solenopsis", "fugax"),
  },
  "Crematogaster scutellaris": {
    scientificName: "Crematogaster scutellaris",
    commonName: "Acrobat Ant",
    queenSize: "7–9 mm",
    lifestyle: "Arboreal; nests in dead wood, bark crevices, and cork oak",
    society: "Monogynous, large colonies (up to 100,000 workers)",
    diet: "Honeydew, insects, tree sap",
    antWikiUrl: antWikiUrl("Crematogaster", "scutellaris"),
  },
  "Myrmica scabrinodis": {
    scientificName: "Myrmica scabrinodis",
    commonName: "Scabrous Myrmica",
    queenSize: "5–6 mm",
    lifestyle: "Ground-nesting in moist meadows and marshes; under stones and in tussocks",
    society: "Polygynous, small to medium colonies",
    diet: "Insects, honeydew, seeds",
    antWikiUrl: antWikiUrl("Myrmica", "scabrinodis"),
  },
  "Ponera coarctata": {
    scientificName: "Ponera coarctata",
    commonName: "Narrow-headed Ponera",
    queenSize: "3–4 mm",
    lifestyle: "Cryptic; nests in soil, under deeply embedded stones, in rotting wood",
    society: "Monogynous, very small colonies (20–100 workers)",
    diet: "Small soil arthropods (specialist predator)",
    antWikiUrl: antWikiUrl("Ponera", "coarctata"),
  },
  "Temnothorax crassispinus": {
    scientificName: "Temnothorax crassispinus",
    commonName: "Thick-spined Acorn Ant",
    queenSize: "3–4 mm",
    lifestyle: "Cavity-nesting; in acorns, bark crevices, rock cracks, and snail shells",
    society: "Monogynous, very small colonies (50–200 workers)",
    diet: "Small insects, honeydew, nectar",
    antWikiUrl: antWikiUrl("Temnothorax", "crassispinus"),
  },
};

export function getSpeciesForSeason(speciesNames: string[]): SpeciesInfo[] {
  return speciesNames
    .map((name) => ALL_SPECIES[name])
    .filter((s): s is SpeciesInfo => s !== undefined);
}
